# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: signals.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'signals.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsignals.proto\x12\tmeowmetry\"3\n\x10SubscribeRequest\x12\r\n\x05types\x18\x01 \x03(\t\x12\x10\n\x08services\x18\x02 \x03(\t\"\x86\x01\n\x06Signal\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03seq\x18\x02 \x01(\x03\x12\n\n\x02ts\x18\x03 \x01(\x03\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x0f\n\x07service\x18\x05 \x01(\t\x12\x10\n\x08severity\x18\x06 \x01(\t\x12\x14\n\x0cpayload_json\x18\x07 \x01(\t\x12\x10\n\x08type_seq\x18\x08 \x01(\x03\x32M\n\x0cSignalStream\x12=\n\tSubscribe\x12\x1b.meowmetry.SubscribeRequest\x1a\x11.meowmetry.Signal0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signals_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBEREQUEST']._serialized_start=28
  _globals['_SUBSCRIBEREQUEST']._serialized_end=79
  _globals['_SIGNAL']._serialized_start=82
  _globals['_SIGNAL']._serialized_end=216
  _globals['_SIGNALSTREAM']._serialized_start=218
  _globals['_SIGNALSTREAM']._serialized_end=295
# @@protoc_insertion_point(module_scope)
